kubectl apply -f images/influxdb/influxdb-secrets.yaml
kubectl apply -f images/influxdb/influxdb-config.yaml
kubectl apply -f images/influxdb/influxdb-deployment.yaml
kubectl apply -f images/influxdb/influxdb-service.yaml
kubectl apply -f images/telegraph/telegraf-config.yaml
kubectl apply -f images/telegraph/telegraf-secrets.yaml
kubectl apply -f images/telegraph/telegraf-deployment.yaml
kubectl apply -f images/grafana/grafana/grafana-deployment.yaml
kubectl apply -f images/grafana/grafana/grafana-service.yaml
