apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage-claim
spec:
# storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: sqlx3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
      matchLabels:
        app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          hostPort: 3306
        volumeMounts:
         - name: mysql-storage
           mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-storage-claim
