apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 26
    name: ssh26
    nodePort: 26
    targetPort: 26 
  - port: 80
    name: nginx80
    nodePort: 80
    targetPort: 80
  - port: 443
    name: nginx443
    nodePort: 443
    targetPort: 443
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
      matchLabels:
        app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 26
        - containerPort: 80
        - containerPort: 443
