apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: phpmyadmin-s
  labels:
    app: phpmyadmin-s
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    name: phpx5000
    nodePort: 5000
    targetPort: 5000
  type: LoadBalancer
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
      matchLabels:
        app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpcontainer
        image: phpmyadmin:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
