apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: sqlx3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
      matchLabels:
        app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: sqlcontainer
        image: mysql:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          hostPort: 3306
