apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: sql-s
  labels:
    app: sql-s
spec:
  type: NodePort
  ports:
  - port: 3306
    name: sqlx3306
    targetPort: 3306
  selector:
    app: sql-s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql
spec:
  selector:
      matchLabels:
        app: sql
  replicas: 1
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sqlcontainer
        image: sql:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
