apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 5050
    name: wordpressx5050
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
      matchLabels:
        app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpresscontainer
        image: wordpress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          hostPort: 5050
